### ISSUE TITLE
introduce the market event logic

### ISSUE THREAD

**Issue by IFFranciscoME** [IteraLabs/atelier#30]
# Context

From the microstructure perspective, the operation of an order-driven market is, well, orders. And the arrival of such can be everything but constant in time. Also, there exists an event-clock vs calendar-clock existing approaches in quantitative finance literature. 

# Problem

Currently, the atelier project doesn't have an event-based logic. In fact, transitions between states is still very incipient, the only way of simulating this is through an iteration of top of the book prices and the model for their evolution.

# Solution

Implement the necessary components to support an event-based logic, in particular, to support an Order book state transition as an effect of the existence of such order (events).

# Success Criteria

There is an Event Generator function, and, a Time Step specification, with which instances of 4 types of events will be generated. 

Events*:  

1. New Limit Order
2. Modify Limit Order
3. Cancel Limit Order
4. New Market Order

Time Step specification: 

- 100ms

* a single instance

**Comment by JoinerDeev** [comment]
This will be very interesting to use actually, looking forward to it
